CREATE TABLE [dbo].[INSCRITO]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Id_alumno] INT NOT NULL, 
    [Cod_curso] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITO_ALUMNO] FOREIGN KEY ([Id_alumno]) REFERENCES [Alumno]([Id]), 
    CONSTRAINT [FK_INSCRITO_CURSO] FOREIGN KEY ([Cod_curso]) REFERENCES [CURSO]([Cod])
)
